apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: volundsgatan-vlg-runners
  namespace: actions-runner-system
spec:
  replicas: 1
  template:
    spec:
      repository: volundsgatan/VLG
      image: ghcr.io/actions/actions-runner-controller/actions-runner-dind:ubuntu-22.04
      dockerdWithinRunnerContainer: true

      containers:
        - name: runner
          volumeMounts:
            - name: docker-secret
              mountPath: "/home/runner/.docker/"
              readOnly: true

      volumes:
        - name: docker-secret
          secret:
            secretName: regcred
            items:
              - key: .dockerconfigjson
                path: config.json
