apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: volundsgatan-vlg-runners
  namespace: actions-runner-system
spec:
  replicas: 1
  template:
    spec:
      repository: volundsgatan/VLG
      image: ghcr.io/actions/actions-runner-controller/actions-runner:ubuntu-22.04
