apiVersion: v1
kind: Namespace
metadata:
  name: homer
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: homer
  namespace: homer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homer
  namespace: homer
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: homer
  template:
    metadata:
      labels:
        app.kubernetes.io/name: homer
    spec:
      serviceAccountName: homer
      securityContext: {}
      containers:
        - name: homer
          image: "ghcr.io/volundsgatan/homer:main"
          imagePullPolicy: Always
          args:
            - "deno"
            - "run"
            - "--allow-net"
            - "--allow-env"
            - "home.ts"
      imagePullSecrets:
        - name: dockerconfigjson-github-com
