kind: Deployment
apiVersion: apps/v1
metadata:
  name: yr-exporter
  namespace: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yr-exporter
  template:
    metadata:
      labels:
        app: yr-exporter
      annotations:
        "prometheus.io/scrape": "true"
        "prometheus.io/port": "9370"
    spec:
      containers:
        - name: yr-exporter
          image: ghcr.io/zegl/yr_exporter:latest
          args:
            - "--listen-addr=:9370"
            - "--location=59.337,18.038,stockholm"
      imagePullSecrets:
      - name: dockerconfigjson-github-com