apiVersion: v1
kind: Namespace
metadata:
  name: registry
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: registry
  namespace: registry
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: registry
  namespace: registry
spec:
  serviceName: "registry"
  replicas: 1
  podManagementPolicy: "Parallel"
  updateStrategy:
    type: "RollingUpdate"
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      serviceAccountName: registry
      containers:
        - name: registry
          image: registry:2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
              name: http
              protocol: TCP
          #readinessProbe:
          #  failureThreshold: 3
          #  httpGet:
          #    path: /robots.txt
          #    port: 3000
          #    scheme: HTTP
          #  initialDelaySeconds: 10
          #  periodSeconds: 30
          #  successThreshold: 1
          #  timeoutSeconds: 2
          #livenessProbe:
          #  failureThreshold: 3
          #  initialDelaySeconds: 30
          #  periodSeconds: 10
          #  successThreshold: 1
          #  tcpSocket:
          #    port: 3000
          #  timeoutSeconds: 1
          resources:
            requests:
              cpu: 250m
              memory: 750Mi
          volumeMounts:
            - mountPath: /var/lib/registry
              name: registry-data
            - mountPath: /auth
              name: auth-config
          env:
          - name: REGISTRY_AUTH
            value: htpasswd
          - name: REGISTRY_AUTH_HTPASSWD_PATH
            value: /auth/htpasswd
          - name: REGISTRY_AUTH_HTPASSWD_REALM
            value: "Registry Realm"
      volumes:
        - name: auth-config
          configMap:
            name: auth
      terminationGracePeriodSeconds: 300
  volumeClaimTemplates:
    - metadata:
        name: registry-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: "5Gi"
---
kind: Service
apiVersion: v1
metadata:
  name: registry
  namespace: registry
spec:
  selector:
    app: registry
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: auth
  namespace: registry
data:
  htpasswd: |-
    zegl:$2y$05$HCbKhrFeidO7yTJ4aIoT/edWMDm4be3lvjVHiSyoibAgqQZWtJio6
