apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tailscale-subnet-router
  namespace: caddy-system
spec:
  replicas: 1
  podManagementPolicy: "Parallel"
  updateStrategy:
    type: "RollingUpdate"
  selector:
    matchLabels:
      app.kubernetes.io/name: tailscale-subnet-router
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tailscale-subnet-router
    spec:
      serviceAccountName: tailscale
      securityContext: {}
      containers:
        - name: tailscale
          imagePullPolicy: Always
          image: "ghcr.io/tailscale/tailscale:latest"
          env:
            - name: TS_KUBE_SECRET
              value: "tailscale-state-subnet-router"
            - name: TS_USERSPACE
              value: "true"
            - name: TS_AUTH_KEY
              valueFrom:
                secretKeyRef:
                  name: tailscale-auth
                  key: TS_AUTH_KEY
                  optional: true
            - name: TS_ROUTES
              value: "10.152.183.0/24,10.1.1.0/24"
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
