apiVersion: v1
kind: ServiceAccount
metadata:
  name: whoami
  namespace: caddy-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami
  namespace: caddy-system
spec:
  replicas: 1
  podManagementPolicy: "Parallel"
  updateStrategy:
    type: "RollingUpdate"
  selector:
    matchLabels:
      app.kubernetes.io/name: whoami
  template:
    metadata:
      labels:
        app.kubernetes.io/name: whoami
    spec:
      serviceAccountName: whoami
      securityContext: {}
      containers:
        - name: whoami
          image: "registry.unicorn-alligator.ts.net/whoami:v2"
          imagePullPolicy: IfNotPresent
          args:
            - "deno"
            - "run"
            - "--allow-net"
            - "--allow-env"
            - "whoami.ts"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources: {}
          env:
          - name: TS_API_KEY
            valueFrom:
              secretKeyRef:
                name: tailscale-api-auth
                key: TS_API_KEY
                optional: true
---
apiVersion: v1
kind: Service
metadata:
  name: whoami
  namespace: caddy-system
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: whoami