apiVersion: v1
kind: Namespace
metadata:
  name: mqtt
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mqtt
  namespace: mqtt
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mqtt
  namespace: mqtt
spec:
  serviceName: "mqtt"
  replicas: 1
  podManagementPolicy: "Parallel"
  updateStrategy:
    type: "RollingUpdate"
  selector:
    matchLabels:
      app: mqtt
  template:
    metadata:
      labels:
        app: mqtt
    spec:
      serviceAccountName: mqtt
      initContainers:
        - name: "init-chown-data"
          image: debian:9
          imagePullPolicy: Always
          command: ["chown", "-R", "65534:65534", "/data"]
          volumeMounts:
            - name: mosquitto-data
              mountPath: /data
              subPath: ""
      containers:
        - name: mqtt
          image: eclipse-mosquitto:2.0.15
          imagePullPolicy: IfNotPresent
          command:
            - "mosquitto"
            - "-c"
            - "/config/mosquitto.conf"
          ports:
            - containerPort: 1883
              name: mqtt-insecure
              protocol: TCP
            - containerPort: 8883
              name: mqtt-secure
              protocol: TCP
          resources:
            requests:
              cpu: 500m
              memory: 1000Mi
          volumeMounts:
            - name: mosquitto-data
              mountPath: /mosquitto
            - name: config-volume
              mountPath: /config
      terminationGracePeriodSeconds: 300
      volumes:
        - name: config-volume
          configMap:
            name: mosquitto-config
  volumeClaimTemplates:
    - metadata:
        name: mosquitto-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: "5Gi"
---
kind: Service
apiVersion: v1
metadata:
  name: mqtt
  namespace: mqtt
spec:
  selector:
    app: mqtt
  ports:
    - protocol: TCP
      port: 1883
      targetPort: 1883
      name: mqtt-insecure
    - protocol: TCP
      port: 8883
      targetPort: 8883
      name: mqtt-secure
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
  namespace: mqtt
data:
  mosquitto.conf: |-
    listener 1883
    allow_anonymous true
    listener 8883
    allow_anonymous false
    password_file /config/mosquitto-auth.txt
  mosquitto-auth.txt: |-
    influx:$7$101$ww+vqsx2sCXIwh3q$uP1YCQI3ZYaCspu8NjCpaYWDH9A84KSS1tp/Siyjbymbp/bpibRLqaUgrTB3+pWzH5afcE3iS/ypk5fet9rtMw==
    mqtt-exporter:$7$101$7kHwHZM31GoX9A6p$Vx1JNXQLb3bTOMGTOxWoCP3hGxRjp83puiaAy3/bj1lIseyM1uzpDBHHZhuDjsjZ3pONifyTBfqmE+UcJNor/g==
    homebridge:$7$101$MrM7UZu5egS/zZZP$Md+0Aiv8npcYKX8oyBPxTXyPkeoltkecmBHl/iIVqo6Ti1K6ArSxuUWL8sZ6ZlihD32kghVRfJn1Dr+fvGXZcg==
