apiVersion: v1
kind: Secret
metadata:
  name: tailscale-state-homebridge
  namespace: homebridge
stringData: {}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tailscale
  namespace: homebridge
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["secrets"]
  # Create can not be restricted to a resource name.
  verbs: ["create"]
- apiGroups: [""] # "" indicates the core API group
  resourceNames: ["tailscale-auth", "tailscale-state-homebridge"]
  resources: ["secrets"]
  verbs: ["get", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tailscale
  namespace: homebridge
subjects:
- kind: ServiceAccount
  name: "homebridge"
roleRef:
  kind: Role
  name: tailscale
  apiGroup: rbac.authorization.k8s.io