version: '3.8'
services:
  mqtt:
    image: eclipse-mosquitto:2.0
    restart: unless-stopped
    volumes:
      - "./mosquitto-data:/mosquitto"
    ports:
      - "1883:1883"
      - "9001:9001"
    command: "mosquitto -c /mosquitto-no-auth.conf"

  zigbee2mqtt:
    container_name: zigbee2mqtt
    restart: unless-stopped
    image: zegl/zigbee2mqtt:edge
    volumes:
      - ./zigbee2mqtt-data:/app/data
      - /run/udev:/run/udev:ro
    ports:
      - 8080:8080
    environment:
      - TZ=Europe/Stockholm
    devices:
      - /dev/ttyACM0:/dev/ttyACM0

  sonos-api:
    network_mode: host
    restart: always
    image: chrisns/docker-node-sonos-http-api
    volumes:
      - ./sonos/settings.json:/app/settings.json
      - ./sonos/clips:/app/static/clips
      - ./sonos/cache:/app/cache
      - ./sonos/presets:/app/presets

  caddy:
    restart: always
    image: caddy:2.5.2-alpine
    ports:
      - 8082:80
      - 443:443
      - 443:443/udp
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./vlg-pi.unicorn-alligator.ts.net.crt:/tls/vlg-pi.unicorn-alligator.ts.net.crt:ro
      - ./vlg-pi.unicorn-alligator.ts.net.key:/tls/vlg-pi.unicorn-alligator.ts.net.key:ro
      - caddy_data:/data

volumes:
  caddy_data:
