version: '3.8'
services:
  mqtt:
    image: eclipse-mosquitto:2.0
    restart: unless-stopped
    volumes:
      - "./mosquitto-data:/mosquitto"
    ports:
      - "1883:1883"
      - "9001:9001"
    command: "mosquitto -c /mosquitto-no-auth.conf"

  zigbee2mqtt:
    container_name: zigbee2mqtt
    restart: unless-stopped
    image: koenkk/zigbee2mqtt:1.27.0
    volumes:
      - ./zigbee2mqtt-data:/app/data
      - /run/udev:/run/udev:ro
    ports:
      - 8080:8080
    environment:
      - TZ=Europe/Stockholm
    devices:
      - /dev/ttyACM0:/dev/ttyACM0

  sonos-api:
    network_mode: host
    restart: always
    image: chrisns/docker-node-sonos-http-api
    volumes:
      - ./sonos/settings.json:/app/settings.json
      - ./sonos/clips:/app/static/clips
      - ./sonos/cache:/app/cache
      - ./sonos/presets:/app/presets

  sonos_proxy:
    restart: always
    image: nginx:1.23
    ports:
      - 8081:80
    volumes:
        - ./nginx/nginx.config:/etc/nginx/conf.d/default.conf:ro
