apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/volundsgatan/VLG
    targetRevision: HEAD
    path: kubernetes/ingress
  destination:
    server: https://kubernetes.default.svc
    namespace: caddy-system
  spec:
    syncPolicy:
      automated: {}