apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mqtt
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/volundsgatan/VLG
    targetRevision: HEAD
    path: kubernetes/mqtt
  destination:
    server: https://kubernetes.default.svc
    namespace: mqtt