apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonos
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/volundsgatan/VLG
    targetRevision: HEAD
    path: kubernetes/sonos
  destination:
    server: https://kubernetes.default.svc
    namespace: sonos
  syncPolicy:
    automated: {}