name: Build Tailscale Whoami

on:
  push:
    branches: ["main"]

jobs:
  build-tailscale-whoami:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Deps
        run: sudo apt-get update && sudo apt-get install -y buildah
      - name: Build
        working-directory: ./tailscale-whoami/
        run: sudo bash build.sh
