name: Build Tailscale Whoami

on:
  push:
    branches: ["main"]

jobs:
  test:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: Deps
        run: sudo apt-get update && sudo apt-get install -y buildah
      - name: Build
        run: sudo bash ./tailscale-whoami/build.sh
