name: Build Tailscale Whoami

on:
  push:
    branches: ["main"]

jobs:
  test:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: bash ./tailscale-whoami/build.sh
